common: &common
  adapter: postgresql
  host:    localhost
  username: developer
  password: '123'

development:
  <<: *common
  database: twitterexchange_dev
  pool: 26

test:
  <<: *common
  database: twitterexchange_test

production:
  adapter: postgresql
  host: 127.0.0.1
  username: twex 
  password: hello_k1tt3 
  database: twex1 
  pool: 26