common: &common
  adapter: postgresql
  username: developer
  password: '123'

development:
  <<: *common
  database: twitterexchange_dev

test:
  <<: *common
  database: twitterexchange_test

production:
  adapter: postgresql
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>