require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MainPageStreamsController do

  # This should return the minimal set of attributes required to create a valid
  # MainPageStream. As you add validations to MainPageStream, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MainPageStreamsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all main_page_streams as @main_page_streams" do
      main_page_stream = MainPageStream.create! valid_attributes
      get :index, {}, valid_session
      assigns(:main_page_streams).should eq([main_page_stream])
    end
  end

  describe "GET show" do
    it "assigns the requested main_page_stream as @main_page_stream" do
      main_page_stream = MainPageStream.create! valid_attributes
      get :show, {:id => main_page_stream.to_param}, valid_session
      assigns(:main_page_stream).should eq(main_page_stream)
    end
  end

  describe "GET new" do
    it "assigns a new main_page_stream as @main_page_stream" do
      get :new, {}, valid_session
      assigns(:main_page_stream).should be_a_new(MainPageStream)
    end
  end

  describe "GET edit" do
    it "assigns the requested main_page_stream as @main_page_stream" do
      main_page_stream = MainPageStream.create! valid_attributes
      get :edit, {:id => main_page_stream.to_param}, valid_session
      assigns(:main_page_stream).should eq(main_page_stream)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MainPageStream" do
        expect {
          post :create, {:main_page_stream => valid_attributes}, valid_session
        }.to change(MainPageStream, :count).by(1)
      end

      it "assigns a newly created main_page_stream as @main_page_stream" do
        post :create, {:main_page_stream => valid_attributes}, valid_session
        assigns(:main_page_stream).should be_a(MainPageStream)
        assigns(:main_page_stream).should be_persisted
      end

      it "redirects to the created main_page_stream" do
        post :create, {:main_page_stream => valid_attributes}, valid_session
        response.should redirect_to(MainPageStream.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved main_page_stream as @main_page_stream" do
        # Trigger the behavior that occurs when invalid params are submitted
        MainPageStream.any_instance.stub(:save).and_return(false)
        post :create, {:main_page_stream => {}}, valid_session
        assigns(:main_page_stream).should be_a_new(MainPageStream)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MainPageStream.any_instance.stub(:save).and_return(false)
        post :create, {:main_page_stream => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested main_page_stream" do
        main_page_stream = MainPageStream.create! valid_attributes
        # Assuming there are no other main_page_streams in the database, this
        # specifies that the MainPageStream created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MainPageStream.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => main_page_stream.to_param, :main_page_stream => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested main_page_stream as @main_page_stream" do
        main_page_stream = MainPageStream.create! valid_attributes
        put :update, {:id => main_page_stream.to_param, :main_page_stream => valid_attributes}, valid_session
        assigns(:main_page_stream).should eq(main_page_stream)
      end

      it "redirects to the main_page_stream" do
        main_page_stream = MainPageStream.create! valid_attributes
        put :update, {:id => main_page_stream.to_param, :main_page_stream => valid_attributes}, valid_session
        response.should redirect_to(main_page_stream)
      end
    end

    describe "with invalid params" do
      it "assigns the main_page_stream as @main_page_stream" do
        main_page_stream = MainPageStream.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MainPageStream.any_instance.stub(:save).and_return(false)
        put :update, {:id => main_page_stream.to_param, :main_page_stream => {}}, valid_session
        assigns(:main_page_stream).should eq(main_page_stream)
      end

      it "re-renders the 'edit' template" do
        main_page_stream = MainPageStream.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MainPageStream.any_instance.stub(:save).and_return(false)
        put :update, {:id => main_page_stream.to_param, :main_page_stream => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested main_page_stream" do
      main_page_stream = MainPageStream.create! valid_attributes
      expect {
        delete :destroy, {:id => main_page_stream.to_param}, valid_session
      }.to change(MainPageStream, :count).by(-1)
    end

    it "redirects to the main_page_streams list" do
      main_page_stream = MainPageStream.create! valid_attributes
      delete :destroy, {:id => main_page_stream.to_param}, valid_session
      response.should redirect_to(main_page_streams_url)
    end
  end

end
